Satranc : ./src/Oyun.cpp ./src/Tahta.cpp ./src/Tas.cpp ./src/Sah.cpp ./src/Vezir.cpp ./src/Fil.cpp ./src/At.cpp ./src/Kale.cpp ./src/Piyon.cpp
	g++ -o ./bin/Satranc ./src/Oyun.cpp ./src/Tahta.cpp ./src/Tas.cpp ./src/Sah.cpp ./src/Vezir.cpp ./src/Fil.cpp ./src/At.cpp ./src/Kale.cpp ./src/Piyon.cpp
